# Generated by Django 3.0.2 on 2020-03-11 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='lon',
        ),
        migrations.AddField(
            model_name='customer',
            name='lng',
            field=models.DecimalField(decimal_places=12, default=None, max_digits=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='lat',
            field=models.DecimalField(decimal_places=12, max_digits=20),
        ),
    ]
