# Generated by Django 3.0.2 on 2020-03-11 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20200311_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='lat',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='lng',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
    ]
