# Generated by Django 3.0.3 on 2020-05-24 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websocket', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='callgroup',
            old_name='name',
            new_name='pin',
        ),
        migrations.AlterField(
            model_name='callgroup',
            name='offer',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
