# Generated by Django 3.0.6 on 2020-07-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makerchecker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='tasktype',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='tasktype',
            name='checker_privilege',
            field=models.CharField(choices=[('Users.manage', 'Manage users'), ('Roles.manage', 'Manage roles'), ('Sales.manage', 'Manage sales'), ('Sales.view', 'View sales'), ('Sales.view.docs', 'View sales documents'), ('Sales.manage.docs', 'Manage sale documents'), ('Sales.reports', 'Sales reports'), ('Sales.view.invoices', 'View Invoices'), ('Sales.create.invoice', 'Create Invoice'), ('Sales.update.invoice', 'Update Invoice'), ('delete_sale_docs_maker', 'Delete Sale Documents Maker'), ('delete_sale_docs_checker', 'Delete Sale Documents Checker'), ('delete_sale_docs_view', 'Delete Sale Documents View')], max_length=40),
        ),
        migrations.AlterField(
            model_name='tasktype',
            name='maker_privilege',
            field=models.CharField(choices=[('Users.manage', 'Manage users'), ('Roles.manage', 'Manage roles'), ('Sales.manage', 'Manage sales'), ('Sales.view', 'View sales'), ('Sales.view.docs', 'View sales documents'), ('Sales.manage.docs', 'Manage sale documents'), ('Sales.reports', 'Sales reports'), ('Sales.view.invoices', 'View Invoices'), ('Sales.create.invoice', 'Create Invoice'), ('Sales.update.invoice', 'Update Invoice'), ('delete_sale_docs_maker', 'Delete Sale Documents Maker'), ('delete_sale_docs_checker', 'Delete Sale Documents Checker'), ('delete_sale_docs_view', 'Delete Sale Documents View')], max_length=40),
        ),
        migrations.AlterField(
            model_name='tasktype',
            name='view_privilege',
            field=models.CharField(choices=[('Users.manage', 'Manage users'), ('Roles.manage', 'Manage roles'), ('Sales.manage', 'Manage sales'), ('Sales.view', 'View sales'), ('Sales.view.docs', 'View sales documents'), ('Sales.manage.docs', 'Manage sale documents'), ('Sales.reports', 'Sales reports'), ('Sales.view.invoices', 'View Invoices'), ('Sales.create.invoice', 'Create Invoice'), ('Sales.update.invoice', 'Update Invoice'), ('delete_sale_docs_maker', 'Delete Sale Documents Maker'), ('delete_sale_docs_checker', 'Delete Sale Documents Checker'), ('delete_sale_docs_view', 'Delete Sale Documents View')], max_length=40),
        ),
    ]
