# Generated by Django 3.0.2 on 2020-03-14 15:15

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='privileges',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Users.manage', 'Manage users'), ('Users.manage', 'Manage roles'), ('Sales.manage', 'Manage sales')], max_length=38, null=True),
        ),
    ]
