# Generated by Django 3.0.6 on 2020-05-23 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200425_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
