# Generated by Django 3.0.6 on 2020-05-23 07:48

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_agent_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='privileges',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Users.manage', 'Manage users'), ('Roles.manage', 'Manage roles'), ('Sales.manage', 'Manage sales'), ('Sales.view', 'View sales'), ('Sales.view.docs', 'View sales documents'), ('Sales.manage.docs', 'Manage sale documents'), ('Sales.reports', 'Sales reports'), ('Sales.create.invoice', 'Create Invoice'), ('Sales.update.invoice', 'Update Invoice')], max_length=139, null=True),
        ),
    ]
