# Generated by Django 3.0.6 on 2020-08-27 19:06

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20200711_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='privileges',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Users.manage', 'Manage users'), ('Roles.manage', 'Manage roles'), ('Sales.manage', 'Manage sales'), ('Sales.view', 'View sales'), ('Sales.view.docs', 'View sales documents'), ('Sales.manage.docs', 'Manage sale documents'), ('Sales.reports', 'Sales reports'), ('Sales.view.invoices', 'View Invoices'), ('Sales.create.invoice', 'Create Invoice'), ('Sales.update.invoice', 'Update Invoice'), ('Sales.invoice.CrDrnote', 'Attach CrDr Note'), ('delete_sale_docs_maker', 'Delete Sale Documents Maker'), ('delete_sale_docs_checker', 'Delete Sale Documents Checker'), ('delete_sale_docs_view', 'Delete Sale Documents View')], max_length=252, null=True),
        ),
    ]
