# Generated by Django 3.1.6 on 2021-05-11 18:33

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_agent_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='privileges',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Home.dashboard', 'View Dashboard'), ('Users.manage', 'Manage users'), ('Roles.manage', 'Manage roles'), ('Sales.manage', 'Manage sales'), ('Sales.view', 'View sales'), ('Sales.view.docs', 'View sales documents'), ('Sales.manage.docs', 'Manage sale documents'), ('Sales.manage.docs.aggregate', 'Manage sale aggregate documents'), ('Sales.reports', 'Sales reports'), ('Sales.view.invoices', 'View Invoices'), ('Sales.create.invoice', 'Create Invoice'), ('Sales.update.invoice', 'Update Invoice'), ('Sales.invoice.CrDrnote', 'Attach CrDr Note'), ('delete_sale_docs_maker', 'Delete Sale Documents Maker'), ('delete_sale_docs_checker', 'Delete Sale Documents Checker'), ('delete_sale_docs_view', 'Delete Sale Documents View')], max_length=295, null=True),
        ),
    ]
