# Generated by Django 3.1.6 on 2021-05-11 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20210511_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='path',
            field=models.CharField(default='/', max_length=40),
        ),
    ]
