# Generated by Django 3.0.2 on 2020-03-14 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('file', models.FileField(upload_to='docs/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.CharField(max_length=20)),
                ('customer_name', models.CharField(max_length=100)),
                ('delivery_note', models.CharField(max_length=100)),
                ('vehicle_number', models.CharField(max_length=100)),
                ('tax_invoice', models.CharField(max_length=100)),
                ('sales_order', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('total_value', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('agent_name', models.CharField(max_length=100)),
                ('agent_code', models.CharField(max_length=100)),
                ('c2_number', models.CharField(max_length=20, null=True)),
                ('assessment_number', models.CharField(max_length=20, null=True)),
                ('exit_number', models.CharField(max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment_doc', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_doc', to='sales.Document')),
                ('c2_doc', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='c2_doc', to='sales.Document')),
                ('exit_doc', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exit_doc', to='sales.Document')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
