# Generated by Django 3.0.2 on 2020-03-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='assessment_number',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='c2_number',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='exit_number',
        ),
        migrations.AddField(
            model_name='document',
            name='ref_number',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sale',
            name='sales_order',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
