# Generated by Django 3.0.6 on 2020-07-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20200711_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='assign_no',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
