# Generated by Django 3.0.2 on 2020-03-16 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20200316_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='assessment_doc',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_assessment', to='sales.Document'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='c2_doc',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_c2', to='sales.Document'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='exit_doc',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_exit', to='sales.Document'),
        ),
    ]
