# Generated by Django 3.0.6 on 2020-08-03 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('makerchecker', '0003_auto_20200714_1833'),
        ('sales', '0003_auto_20200711_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='makerchecker.Task'),
        ),
    ]
