# Generated by Django 3.0.2 on 2020-03-16 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_auto_20200316_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='assessment_doc',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='c2_doc',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='exit_doc',
        ),
        migrations.AddField(
            model_name='document',
            name='doc_type',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='sale',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='docs', to='sales.Sale'),
            preserve_default=False,
        ),
    ]
