# Generated by Django 3.0.2 on 2020-03-31 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_auto_20200316_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='ref_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('ref_number', 'doc_type')},
        ),
    ]
