# Generated by Django 3.0.2 on 2020-03-31 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='agent_name',
        ),
        migrations.AddField(
            model_name='sale',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.Agent'),
        ),
    ]
