# Generated by Django 3.0.2 on 2020-03-31 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_agent'),
        ('sales', '0008_auto_20200331_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Agent'),
        ),
        migrations.DeleteModel(
            name='Agent',
        ),
    ]
