# Generated by Django 3.0.2 on 2020-04-25 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_auto_20200331_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='quantity2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='total_value2',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
