# Generated by Django 3.1.6 on 2021-03-19 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_auto_20210319_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aggregatedocument',
            name='truck',
        ),
        migrations.AddField(
            model_name='aggregatesale',
            name='bal_used_on',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.aggregatesale'),
        ),
    ]
