# Generated by Django 3.1.6 on 2021-03-19 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_auto_20210319_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aggregatedocument',
            name='aggregate_sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docs', to='sales.aggregatesale'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='aggregate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='sales.aggregatesale'),
        ),
    ]
