# Generated by Django 3.0.2 on 2020-04-25 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_auto_20200425_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='agent_code',
        ),
    ]
