# Generated by Django 3.1.6 on 2021-03-19 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_auto_20210319_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='aggregate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='sales.aggregatesale'),
        ),
    ]
