# Generated by Django 3.0.6 on 2020-05-22 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
