# Generated by Django 3.1.6 on 2021-04-08 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_auto_20200711_1437'),
        ('makerchecker', '0005_auto_20210322_1631'),
        ('users', '0017_auto_20210322_1631'),
        ('sales', '0013_auto_20210319_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.agent'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='aggregate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='sales.aggregatesale'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='assign_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='invoices.invoice'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='quantity2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='makerchecker.task'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_value2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
