# Generated by Django 3.1.6 on 2021-04-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_auto_20210408_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregatesale',
            name='category',
            field=models.IntegerField(default=3),
        ),
    ]
