# Generated by Django 3.1.6 on 2021-05-04 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_auto_20210423_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aggregatesale',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='aggregatesale',
            name='updated_at',
        ),
    ]
