# Generated by Django 3.0.6 on 2020-05-23 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_auto_20200523_1128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='amount',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='tonage',
            new_name='value',
        ),
    ]
