# Generated by Django 3.1.6 on 2021-05-04 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_auto_20210504_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='aggregate',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='sales.aggregatesale'),
        ),
    ]
