# Generated by Django 3.1.6 on 2021-05-04 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_auto_20210504_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregatesale',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='aggregatesale',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
