# Generated by Django 3.0.6 on 2020-05-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_auto_20200523_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='carrier_type',
            field=models.CharField(default='header', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('ref_number', 'doc_type', 'carrier_type')},
        ),
    ]
