# Generated by Django 3.1.6 on 2021-05-04 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_auto_20210504_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aggregatesale',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='aggregatesale',
            name='updated_at',
        ),
    ]
