# Generated by Django 3.0.6 on 2020-05-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_auto_20200526_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='truck',
            field=models.CharField(default='head', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('ref_number', 'doc_type', 'truck')},
        ),
        migrations.RemoveField(
            model_name='document',
            name='carrier_type',
        ),
    ]
