# Generated by Django 3.0.6 on 2020-05-27 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0022_auto_20200526_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='vehicle_number_trailer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
