# Generated by Django 3.0.6 on 2020-05-31 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0023_sale_vehicle_number_trailer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Params',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(max_length=4)),
                ('y', models.IntegerField(max_length=4)),
                ('h', models.IntegerField(max_length=4)),
                ('w', models.IntegerField(max_length=4)),
                ('threshold', models.IntegerField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('letter', models.CharField(max_length=40)),
                ('key', models.CharField(max_length=40)),
                ('regex', models.CharField(max_length=40)),
                ('params', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sales.Params')),
            ],
        ),
    ]
