# Generated by Django 3.2.3 on 2021-05-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0024_auto_20210522_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='missing_c2',
            field=models.IntegerField(null=True),
        ),
    ]
