# Generated by Django 3.0.6 on 2020-05-31 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0024_params_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='schema',
            name='prefix',
            field=models.CharField(default=None, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='params',
            name='h',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='params',
            name='threshold',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='params',
            name='w',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='params',
            name='x',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='params',
            name='y',
            field=models.IntegerField(),
        ),
    ]
