# Generated by Django 3.2.3 on 2021-05-22 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0025_sale_missing_c2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='missing_c2',
        ),
    ]
