# Generated by Django 3.0.6 on 2020-05-31 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0025_auto_20200531_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='prefix',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
