# Generated by Django 3.2.3 on 2021-05-27 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0026_remove_sale_missing_c2'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
