# Generated by Django 3.0.6 on 2020-06-05 13:24

from django.db import migrations, models
import sales.models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0026_auto_20200531_1628'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Batches'},
        ),
        migrations.AddField(
            model_name='batch',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='schema',
            name='prefix',
            field=sales.models.NonStrippingCharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='schema',
            name='regex',
            field=sales.models.NonStrippingCharField(max_length=40),
        ),
    ]
