# Generated by Django 3.2.3 on 2021-06-07 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0027_document_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='docs_flag',
            field=models.IntegerField(default=1),
        ),
    ]
