# Generated by Django 3.0.6 on 2020-06-10 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0028_auto_20200610_1809'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InvoiceDocument',
            new_name='InvoiceDoc',
        ),
    ]
