# Generated by Django 3.0.6 on 2020-07-09 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
        ('sales', '0030_document_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invoicedoc',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='invoicedoc',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='schema',
            name='params',
        ),
        migrations.AlterField(
            model_name='sale',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='invoices.Invoice'),
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='InvoiceDoc',
        ),
        migrations.DeleteModel(
            name='Params',
        ),
        migrations.DeleteModel(
            name='Schema',
        ),
    ]
