# Generated by Django 3.0.6 on 2020-07-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0031_auto_20200709_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='serial_no',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
