# Generated by Django 3.0.6 on 2020-07-11 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0032_sale_serial_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='serial_no',
            new_name='assign_no',
        ),
    ]
